const TodoConstants =  {
  'TODO_CREATE' : 'TODO_CREATE',
  'TODO_DESTROY': 'TODO_DESTROY',
  'TODO_UPDATE_TEXT' : 'TODO_UPDATE_TEXT',
  'TODO_COMPLETE' : 'TODO_COMPLETE',
  'TODO_UNDO_COMPLETE' : 'TODO_UNDO_COMPLETE',
  'TODO_DESTROY_COMPLETED' : 'TODO_DESTROY_COMPLETED',
  'TODO_TOGGLE_COMPLETE_ALL' : 'TODO_TOGGLE_COMPLETE_ALL'
}

export default TodoConstants
